server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 1234

# Mustache ??? ???? ?? ??? ??? ??? ?? ?? ??? ?? ??
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
#    open-in-view: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 794728723624-4fbqthdk5gecoog9mnkh9vg2rjctck2h.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
